/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Registro.PrototypeClasificacionResiduo;
import Modelo.Registro.PrototypeDireccion;
import Modelo.Registro.PrototypeResiduo;
import Modelo.Registro.PrototypeUsuario;
import Modelo.SistemaGestionResiduosFacade;
import Modelo.SistemaGestionResiduosFacadeImpl;
import Vista.PatronObserver.BotonObservador;
import Vista.PatronObserver.Formulario;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author sankef
 */
public class VentanaRegistro extends javax.swing.JPanel {
    
    private Formulario formulario; 
    private Formulario formulario2;
    private Formulario formulario3;
    
    // Prototipos para guardar datos en memoria
    private PrototypeDireccion direccion = new PrototypeDireccion();
    private PrototypeUsuario usuario = new PrototypeUsuario();
    private PrototypeClasificacionResiduo clasificacion = new PrototypeClasificacionResiduo();
    private PrototypeResiduo residuo = new PrototypeResiduo();

    // Puedes necesitar una instancia de la fachada si la utilizas directamente para guardar
    private SistemaGestionResiduosFacade fachada = new SistemaGestionResiduosFacadeImpl();
    /**
     * Creates new form VentanaRegistro
     */
    public VentanaRegistro() {
        initComponents();
        
        // Inicializamos el sujeto (Formulario)
        formulario = new Formulario();
        formulario2 = new Formulario();
        formulario3 = new Formulario();

        // Crear un observador para el botón y lo registramos en el sujeto
        BotonObservador botonObservador = new BotonObservador(this.btnSiguiente1);
        formulario.agregarObservador(botonObservador);  // Registrar el botón como observador
        // Configurar los eventos para los campos de texto del Paso 1
        camposPaso1();
        
        BotonObservador botonObservador2 = new BotonObservador(this.btnSiguiente2);
        formulario2.agregarObservador(botonObservador2);  // Registrar el botón como observador
        camposPaso2();
       
        BotonObservador botonObservador3 = new BotonObservador(this.btnFinalizar);
        formulario3.agregarObservador(botonObservador3);  // Registrar el botón como observador
        camposPaso3();
    }

    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelPaso1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Pais = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtDistrito = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtPostal = new javax.swing.JTextField();
        txtReferencia = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnAnterior1 = new javax.swing.JButton();
        btnSiguiente1 = new javax.swing.JButton();
        panelPaso2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNombreClaResiduo = new javax.swing.JTextField();
        txtDescripcionClaResiduo = new javax.swing.JTextField();
        txtColorClaResiduo = new javax.swing.JTextField();
        txtIconoClaResiduo = new javax.swing.JTextField();
        btnAnterior2 = new javax.swing.JButton();
        btnSiguiente2 = new javax.swing.JButton();
        panelPaso3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNombreResiduo = new javax.swing.JTextField();
        txtDescripcionResiduo = new javax.swing.JTextField();
        txtPesoResiduo = new javax.swing.JTextField();
        txtPeligrosidadResiduo = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(700, 400));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setPreferredSize(new java.awt.Dimension(700, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(153, 255, 153));
        jTabbedPane1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(700, 400));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(700, 400));

        panelPaso1.setBackground(new java.awt.Color(255, 204, 204));
        panelPaso1.setMaximumSize(new java.awt.Dimension(700, 400));

        Pais.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Pais.setText("Pais");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel7.setText("Ciudad");

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel8.setText("Distrito");

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel9.setText("Direccion");

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel10.setText("Cod. Postal");

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel11.setText("Referencia");

        txtPais.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtCiudad.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtDistrito.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtDireccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtPostal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtReferencia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Pais, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pais, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel2.setText("Apellido");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel3.setText("Correo");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel4.setText("Telefono");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel5.setText("Contraseña");

        txtNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtApellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtCorreo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtContraseña.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtApellido))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCorreo))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtContraseña)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        btnAnterior1.setBackground(new java.awt.Color(255, 51, 51));
        btnAnterior1.setText("Anterior");

        btnSiguiente1.setBackground(new java.awt.Color(51, 204, 255));
        btnSiguiente1.setText("Siguiente");
        btnSiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPaso1Layout = new javax.swing.GroupLayout(panelPaso1);
        panelPaso1.setLayout(panelPaso1Layout);
        panelPaso1Layout.setHorizontalGroup(
            panelPaso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaso1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelPaso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnterior1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(panelPaso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelPaso1Layout.setVerticalGroup(
            panelPaso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaso1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelPaso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPaso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSiguiente1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnAnterior1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Paso 1 (usuario y direccion )", panelPaso1);

        panelPaso2.setBackground(new java.awt.Color(255, 204, 204));
        panelPaso2.setMaximumSize(new java.awt.Dimension(700, 400));
        panelPaso2.setMinimumSize(new java.awt.Dimension(700, 400));

        Nombre.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        Nombre.setText("Nombre");

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel12.setText("Descripcion");

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel13.setText("Icono");

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel14.setText("Color");

        txtNombreClaResiduo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtDescripcionClaResiduo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtColorClaResiduo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtIconoClaResiduo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreClaResiduo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtColorClaResiduo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIconoClaResiduo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcionClaResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreClaResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcionClaResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColorClaResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIconoClaResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        btnAnterior2.setBackground(new java.awt.Color(255, 51, 51));
        btnAnterior2.setText("Anterior");

        btnSiguiente2.setBackground(new java.awt.Color(51, 204, 255));
        btnSiguiente2.setText("Siguiente");
        btnSiguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPaso2Layout = new javax.swing.GroupLayout(panelPaso2);
        panelPaso2.setLayout(panelPaso2Layout);
        panelPaso2Layout.setHorizontalGroup(
            panelPaso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaso2Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(panelPaso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPaso2Layout.createSequentialGroup()
                        .addComponent(btnAnterior2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnSiguiente2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        panelPaso2Layout.setVerticalGroup(
            panelPaso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaso2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPaso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnterior2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Paso 2 ( Clasificacion de residuo )", panelPaso2);

        panelPaso3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel15.setText("Nombre");

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel16.setText("Descripcion");

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel17.setText("Peso");

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel18.setText("Peligrosidad");

        txtNombreResiduo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtDescripcionResiduo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtPesoResiduo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtPeligrosidadResiduo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPeligrosidadResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(13, 13, 13)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescripcionResiduo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtPesoResiduo)
                            .addComponent(txtNombreResiduo))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcionResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesoResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPeligrosidadResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Anterior");

        btnFinalizar.setBackground(new java.awt.Color(255, 255, 51));
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPaso3Layout = new javax.swing.GroupLayout(panelPaso3);
        panelPaso3.setLayout(panelPaso3Layout);
        panelPaso3Layout.setHorizontalGroup(
            panelPaso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaso3Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(panelPaso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPaso3Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        panelPaso3Layout.setVerticalGroup(
            panelPaso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaso3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPaso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Paso 3 ( Residuo )", panelPaso3);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 470));
    }// </editor-fold>//GEN-END:initComponents

    //boton siguiente del panel 1
    private void btnSiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente1ActionPerformed
          if (guardarDatosParciales(0)) { // Llama al método adaptado para la pestaña 0
        jTabbedPane1.setSelectedIndex(1);
        // Si tu nuevo formulario tiene lógica para habilitar pestañas como el anterior
        // jTabbedPane1.setEnabledAt(1, true);
    } else {
        JOptionPane.showMessageDialog(this, "Por favor complete todos los campos requeridos en esta sección.",
                                      "Formulario incompleto", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnSiguiente1ActionPerformed

    //boton siguiente del panel 2
    private void btnSiguiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente2ActionPerformed
         if (guardarDatosParciales(1)) { // Llama al método adaptado para la pestaña 1
        jTabbedPane1.setSelectedIndex(2);
        // Si tu nuevo formulario tiene lógica para habilitar pestañas como el anterior
        // jTabbedPane1.setEnabledAt(2, true);
    } else {
        JOptionPane.showMessageDialog(this, "Por favor complete todos los campos requeridos en esta sección.",
                                      "Formulario incompleto", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnSiguiente2ActionPerformed

    //finalizar con el registro
    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        if (guardarDatosParciales(2)) { // Llama al método adaptado para la pestaña 2 (la última)
        boolean exito = guardarTodoEnBD();
        if (exito) {
            JOptionPane.showMessageDialog(this, "Datos guardados exitosamente.",
                                          "Registro Completo", JOptionPane.INFORMATION_MESSAGE);
            limpiarFormulario(); // Limpia y resetea el formulario
            // Si necesitas deshabilitar pestañas después de un registro exitoso, hazlo aquí:
            // jTabbedPane1.setEnabledAt(1, false);
            // jTabbedPane1.setEnabledAt(2, false);
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar los datos. Por favor, intente de nuevo.",
                                          "Error de Registro", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor complete todos los campos requeridos en esta sección.",
                                      "Formulario incompleto", JOptionPane.WARNING_MESSAGE);
    }
        
    }//GEN-LAST:event_btnFinalizarActionPerformed

    // Este método iría dentro de tu clase NuevoFormulario
private void limpiarFormulario() {
    // Limpia campos de Usuario y Dirección
    txtNombre.setText("");
    txtApellido.setText("");
    txtTelefono.setText("");
    txtCorreo.setText("");
    txtContraseña.setText(""); // Para JPasswordField
    txtPais.setText("Perú");
    txtCiudad.setText("");
    txtDistrito.setText("");
    txtDireccion.setText("");
    txtPostal.setText("");
    txtReferencia.setText("");

    // Limpia campos de Clasificación
    txtNombreClaResiduo.setText("");
    txtDescripcionClaResiduo.setText("");
    txtColorClaResiduo.setText("");
    txtIconoClaResiduo.setText("");

    // Limpia campos de Residuo
    txtNombreResiduo.setText("");
    txtDescripcionResiduo.setText("");
    txtPesoResiduo.setText("Kilogramos"); // Si es la unidad de medida predeterminada
    txtPeligrosidadResiduo.setText("");

    // Resetea los objetos prototipo creando nuevas instancias
    direccion = new PrototypeDireccion();
    usuario = new PrototypeUsuario();
    clasificacion = new PrototypeClasificacionResiduo();
    residuo = new PrototypeResiduo();

    // Además, podrías querer deshabilitar las pestañas nuevamente
    jTabbedPane1.setSelectedIndex(0); // Vuelve a la primera pestaña
    // Si tienes un mecanismo para deshabilitar las otras pestañas (como en el constructor original)
    // jTabbedPane1.setEnabledAt(1, false);
    // jTabbedPane1.setEnabledAt(2, false);
}
    
    // Este método iría dentro de tu clase NuevoFormulario
private boolean guardarDatosParciales(int tabIndex) {
    switch (tabIndex) {
        case 0: // Pestaña de Usuario y Dirección
            // Validar campos de Usuario
            if (txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty() ||
                txtCorreo.getText().isEmpty() || new String(txtContraseña.getPassword()).isEmpty()) { // Uso de JPasswordField
                return false;
            }
            // Validar campos de Dirección
            if (txtDireccion.getText().isEmpty() || txtCiudad.getText().isEmpty() ||
                txtDistrito.getText().isEmpty()) { // Puedes añadir más validaciones si es necesario
                return false;
            }

            usuario.setNombre(txtNombre.getText());
            usuario.setApellido(txtApellido.getText());
            usuario.setCorreo(txtCorreo.getText());
            usuario.setTelefono(txtTelefono.getText());
            usuario.setContrasena_hash(new String(txtContraseña.getPassword())); // Obtener contraseña de JPasswordField

            direccion.setDireccion(txtDireccion.getText());
            direccion.setCiudad(txtCiudad.getText());
            direccion.setDistrito(txtDistrito.getText());
            direccion.setCodigo_postal(txtPostal.getText()); // Usando txtPostal
            direccion.setPais(txtPais.getText());
            direccion.setReferencia(txtReferencia.getText());
            return true;

        case 1: // Pestaña de Clasificación (anteriormente tabIndex 1)
            if (txtNombreClaResiduo.getText().isEmpty() || txtDescripcionClaResiduo.getText().isEmpty()) {
                return false;
            }
            clasificacion.setNombre(txtNombreClaResiduo.getText());
            clasificacion.setDescripcion(txtDescripcionClaResiduo.getText());
            clasificacion.setColor_codigo(txtColorClaResiduo.getText());
            clasificacion.setIcono(txtIconoClaResiduo.getText());
            return true;

        case 2: // Pestaña de Residuo (anteriormente tabIndex 2)
            if (txtNombreResiduo.getText().isEmpty() || txtDescripcionResiduo.getText().isEmpty() ||
                txtPesoResiduo.getText().isEmpty()) { // ¡Considera validar txtPesoResiduo como número!
                return false;
            }
            residuo.setNombre(txtNombreResiduo.getText());
            residuo.setDescripcion(txtDescripcionResiduo.getText());
            residuo.setUnidad_medida(txtPesoResiduo.getText()); // Asumiendo que txtPesoResiduo es la unidad de medida
            residuo.setPeligrosidad(txtPeligrosidadResiduo.getText());
            return true;

        default:
            return false;
    }
}

// Este método iría dentro de tu clase NuevoFormulario
private boolean guardarTodoEnBD() {
    SistemaGestionResiduosFacade fachada = new SistemaGestionResiduosFacadeImpl();
    return fachada.registrarFlujoCompleto(usuario, direccion, clasificacion, residuo);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Pais;
    private javax.swing.JButton btnAnterior1;
    private javax.swing.JButton btnAnterior2;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnSiguiente1;
    private javax.swing.JButton btnSiguiente2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelPaso1;
    private javax.swing.JPanel panelPaso2;
    private javax.swing.JPanel panelPaso3;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtColorClaResiduo;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDescripcionClaResiduo;
    private javax.swing.JTextField txtDescripcionResiduo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDistrito;
    private javax.swing.JTextField txtIconoClaResiduo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreClaResiduo;
    private javax.swing.JTextField txtNombreResiduo;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPeligrosidadResiduo;
    private javax.swing.JTextField txtPesoResiduo;
    private javax.swing.JTextField txtPostal;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

 
    public void camposPaso1(){
        txtNombre.addCaretListener(e -> actualizarEstadoFormulario());
        txtApellido.addCaretListener(e -> actualizarEstadoFormulario());
        txtCorreo.addCaretListener(e -> actualizarEstadoFormulario());
        txtTelefono.addCaretListener(e -> actualizarEstadoFormulario());
        txtPais.addCaretListener(e -> actualizarEstadoFormulario());
        txtCiudad.addCaretListener(e -> actualizarEstadoFormulario());
        txtDistrito.addCaretListener(e -> actualizarEstadoFormulario());
        txtDireccion.addCaretListener(e -> actualizarEstadoFormulario());
        txtPostal.addCaretListener(e -> actualizarEstadoFormulario());
        txtReferencia.addCaretListener(e -> actualizarEstadoFormulario());
        txtContraseña.addCaretListener(e -> actualizarEstadoFormulario());
        
        
    }
    // Actualizar el estado del formulario cada vez que un campo cambie
    public void actualizarEstadoFormulario() {
        // Verifica que todos los campos estén llenos
        boolean formularioCompleto = !txtNombre.getText().isEmpty() &&
                                      !txtApellido.getText().isEmpty() &&
                                      !txtCorreo.getText().isEmpty() &&
                                      !txtTelefono.getText().isEmpty() &&
                                      !txtPais.getText().isEmpty() &&
                                      !txtCiudad.getText().isEmpty() &&
                                      !txtDistrito.getText().isEmpty() &&
                                      !txtDireccion.getText().isEmpty() &&
                                      !txtPostal.getText().isEmpty() &&
                                      !txtReferencia.getText().isEmpty() &&
                                      !new String(txtContraseña.getPassword()).isEmpty(); // Verifica que la contraseña no esté vacía
        // Notificar el estado actualizado del formulario a los observadores (botones)
        formulario.setFormularioCompleto(formularioCompleto);  // Cambia el estado del formulario y notifica a los observadores
    }
    
    public void camposPaso2(){
        // --- ¡Añade CaretListener a los nuevos campos! ---
        txtDescripcionClaResiduo.addCaretListener(e -> actualizarCampo2());
        txtIconoClaResiduo.addCaretListener(e -> actualizarCampo2());
        txtNombreClaResiduo.addCaretListener(e -> actualizarCampo2());
        txtColorClaResiduo.addCaretListener(e -> actualizarCampo2());
    }
    public void actualizarCampo2(){
        // Verifica que todos los campos estén llenos
        boolean formularioCompleto2 = // --- ¡Añade los nuevos campos a la condición de validación! ---
                                     !txtDescripcionClaResiduo.getText().isEmpty() &&
                                     !txtIconoClaResiduo.getText().isEmpty() &&
                                     !txtNombreClaResiduo.getText().isEmpty() &&
                                     !txtColorClaResiduo.getText().isEmpty();
        // Notificar el estado actualizado del formulario a los observadores (botones)
        formulario2.setFormularioCompleto(formularioCompleto2);  // Cambia el estado del formulario y notifica a los observadores
    }
    
    
    //campos 3
     public void camposPaso3(){
        // --- ¡Añade CaretListener a los nuevos campos! ---
        txtDescripcionResiduo.addCaretListener(e -> actualizarCampo3());
        txtPeligrosidadResiduo.addCaretListener(e -> actualizarCampo3());
        txtNombreResiduo.addCaretListener(e -> actualizarCampo3());
        txtPesoResiduo.addCaretListener(e -> actualizarCampo3());
    }
     
     public void actualizarCampo3(){
        // Verifica que todos los campos estén llenos
        boolean formularioCompleto3 = // --- ¡Añade los nuevos campos a la condición de validación! ---
                                     !txtDescripcionResiduo.getText().isEmpty() &&
                                     !txtPeligrosidadResiduo.getText().isEmpty() &&
                                     !txtNombreResiduo.getText().isEmpty() &&
                                     !txtPesoResiduo.getText().isEmpty();
        // Notificar el estado actualizado del formulario a los observadores (botones)
        formulario3.setFormularioCompleto(formularioCompleto3);  // Cambia el estado del formulario y notifica a los observadores
    } 
     
    
       
    
    public JTextField getTxtApellido() {
        return txtApellido;
    }

    public void setTxtApellido(JTextField txtApellido) {
        this.txtApellido = txtApellido;
    }

    public JTextField getTxtCiudad() {
        return txtCiudad;
    }

    public void setTxtCiudad(JTextField txtCiudad) {
        this.txtCiudad = txtCiudad;
    }

    public JPasswordField getTxtContraseña() {
        return txtContraseña;
    }

    public void setTxtContraseña(JPasswordField txtContraseña) {
        this.txtContraseña = txtContraseña;
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public void setTxtCorreo(JTextField txtCorreo) {
        this.txtCorreo = txtCorreo;
    }

    public JTextField getTxtDireccion() {
        return txtDireccion;
    }

    public void setTxtDireccion(JTextField txtDireccion) {
        this.txtDireccion = txtDireccion;
    }

    public JTextField getTxtDistrito() {
        return txtDistrito;
    }

    public void setTxtDistrito(JTextField txtDistrito) {
        this.txtDistrito = txtDistrito;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public JTextField getTxtPais() {
        return txtPais;
    }

    public void setTxtPais(JTextField txtPais) {
        this.txtPais = txtPais;
    }

    public JTextField getTxtPostal() {
        return txtPostal;
    }

    public void setTxtPostal(JTextField txtPostal) {
        this.txtPostal = txtPostal;
    }

    public JTextField getTxtReferencia() {
        return txtReferencia;
    }

    public void setTxtReferencia(JTextField txtReferencia) {
        this.txtReferencia = txtReferencia;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public void setTxtTelefono(JTextField txtTelefono) {
        this.txtTelefono = txtTelefono;
    }

    public JButton getBtnAnterior1() {
        return btnAnterior1;
    }

    public void setBtnAnterior1(JButton btnAnterior1) {
        this.btnAnterior1 = btnAnterior1;
    }

    public JButton getBtnSiguiente1() {
        return btnSiguiente1;
    }

    public void setBtnSiguiente1(JButton btnSiguiente1) {
        this.btnSiguiente1 = btnSiguiente1;
    }

    public JTextField getTxtColorClaResiduo() {
        return txtColorClaResiduo;
    }

    public void setTxtColorClaResiduo(JTextField txtColorClaResiduo) {
        this.txtColorClaResiduo = txtColorClaResiduo;
    }

    public JTextField getTxtDescripcionClaResiduo() {
        return txtDescripcionClaResiduo;
    }

    public void setTxtDescripcionClaResiduo(JTextField txtDescripcionClaResiduo) {
        this.txtDescripcionClaResiduo = txtDescripcionClaResiduo;
    }

    public JTextField getTxtIconoClaResiduo() {
        return txtIconoClaResiduo;
    }

    public void setTxtIconoClaResiduo(JTextField txtIconoClaResiduo) {
        this.txtIconoClaResiduo = txtIconoClaResiduo;
    }

    public JTextField getTxtNombreClaResiduo() {
        return txtNombreClaResiduo;
    }

    public void setTxtNombreClaResiduo(JTextField txtNombreClaResiduo) {
        this.txtNombreClaResiduo = txtNombreClaResiduo;
    }


    
}
